services:
  backend:
    image: horpynka-backend-dev
    env_file:
      - .env.development
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      NODE_ENV: development
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      COOKIE_SECRET: ${COOKIE_SECRET}
      PASSWORD_HASH_SALT: ${PASSWORD_HASH_SALT}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "yarn install --frozen-lockfile --check-files --production=false && yarn migration:run && yarn dev"

  db:
    image: postgres:16-alpine
    env_file:
      - .env.development
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "4001:${DB_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: